const actionTypes = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  TOGGLE_TODO: "TOGGLE_TODO",
};

export default actionTypes;
